# Generated by Django 5.2.4 on 2025-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_store', '0002_alter_userprofile_country_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('order_inquiry', 'Order Inquiry'), ('product_support', 'Product Support'), ('plant_care', 'Plant Care Advice'), ('general', 'General Question'), ('complaint', 'Complaint'), ('partnership', 'Partnership Inquiry')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
