# Generated by Django 5.2.4 on 2025-08-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_store', '0006_customersuggestion_dislikes_customersuggestion_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLikeDislike',
        ),
    ]
