# Generated by Django 5.2.5 on 2025-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_store', '0008_uservote'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
